project:
  type: website

website:
  title: "EEGManySteps"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: news.qmd
        text: News
      - href: team.qmd
        text: Team
      - href: datasets.qmd
        text: Datasets

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    grid:
      sidebar-width: 50px

execute:
  freeze: auto